### ISSUE TITLE
Kernelsu safemode issue

### ISSUE THREAD

**Issue by bggRGjQaUbCoE** [pascua28/android_kernel_samsung_sm8250#1]
The input hook will not stop correctly if integrate kernelsu manually with kprobes enabled. The device still can enter safemode by pressing volume button after booted.

**Comment by pascua28** [comment]
Yeah. I realized that when the phone is also in safe mode, by pressing volume down during boot, you can't open downloaded apps so it still defeats the purpose of booting your phone so you can remove some problematic modules. I could also add a check when /data partition is mounted so it will stop listening for volume down event but unfortunately, I tried it and kernelsu won't enter safemode if Andoid itself is in safe mode.

TL;DR. I'm reverting it

**Comment by pascua28** [comment]
[1.patch](https://github.com/pascua28/android_kernel_samsung_sm8250/files/11472097/1.patch)
Hi! You can try this patch. What I did was to only listen to volume down inputs before data is decrypted.

Not sure if this is wip as I added a new header to prevent editing an existing header and so I won't have to recompile the whole kernel. :D
