### ISSUE TITLE
Stock camera issue on PK v8.0

### ISSUE THREAD

**Issue by ghost** [pascua28/android_kernel_samsung_sm8250#3]
Hello dear Samuel!
I was wondering can PrimeKernel v8.0 be somehow connected to stock camera issues on the May/June stock ROM's?

I don't know how to describe the issue other than that when you open the Camera app it can immediately show a small black and white camera icon in the center and freeze or it can work properly a few seconds (both photo and video mode) and then freeze. Force close doesn't do anything. Only reboot fixes the issue until it freezes again.
The reason I am asking is because when I downgraded to PrimeKernel 7.2 the issue went away.
Can you please look into this?

S20 FE 5G (DBT) / Android 13 / OneUI 5.1 / Unlocked bootloader / Stock G781BXXS5HWD4 and G781BXXU6HWE6

**Comment by anuragpindoriya** [comment]
Can you attache screen shot please

**Comment by ghost** [comment]
> Can you attache screen shot please

![1](https://github.com/pascua28/android_kernel_samsung_sm8250/assets/138368041/2a6247f2-1032-42b4-a9aa-1740e51a1370)
![2](https://github.com/pascua28/android_kernel_samsung_sm8250/assets/138368041/c4e0ea3c-db26-4619-8a80-4a62cb13edf9)

https://github.com/pascua28/android_kernel_samsung_sm8250/assets/138368041/b1acc323-6665-4707-9d4c-30f6d090bd82

**Comment by pascua28** [comment]
@iamnytskyi, have you tried going back to stock and see if the issue appears?

**Comment by ghost** [comment]
@pascua28
No issues on stock or on PrimeKernel v.7.2.
It appears to be 8.0 issue. Also another person on XDA PrimeKernel thread confirmed that he had the same issue and reverted back to 7.2 to resolve it.

**Comment by pascua28** [comment]
> @pascua28 No issues on stock or on PrimeKernel v.7.2. It appears to be 8.0 issue. Also another person on XDA PrimeKernel thread confirmed that he had the same issue and reverted back to 7.2 to resolve it.

Ok. Seems like some dma issue. Will look into it

**Comment by pascua28** [comment]
> @pascua28 No issues on stock or on PrimeKernel v.7.2. It appears to be 8.0 issue. Also another person on XDA PrimeKernel thread confirmed that he had the same issue and reverted back to 7.2 to resolve it.

Just to verify the issue, can you please also check if the OIS works (you can move your phone a bit and notice that the cameras move too) even after closing the camera app?

**Comment by pascua28** [comment]
Confirmed that this is an issue with GCC's PGO
